name: Build and Test
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.4.0
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
      - name: Build the crate
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          args: --release --all-features
      - name: Test the crate
        uses: actions-rs/cargo@v1.0.1
        with:
         command: test
